server:
  port: 8083

spring:
  application:
    name: qooerp-scm
  profiles:
    active: dev

# Nacos配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: DEFAULT_GROUP
        enabled: true

# 服务配置
service:
  name: 供应链管理服务
  version: 1.0.0
